---
version: "3"
services:
  frontend:
    image: frontend-react
    build: ./frontend-react
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: backend-gpu
    build: ./backend-gpu
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./backend-gpu/logs:/backend-gpu/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  database:
    image: mysql:8.3.0
    env_file:
      - .env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx
    command: >
      /bin/sh -c "
      envsubst '$${FRONTEND_CONTAINER_PORT} $${BACKEND_CONTAINER_PORT} $${NGINX_CONTAINER_PORT}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && 
      nginx -g 'daemon off;'"
    ports:
      - "80:${NGINX_CONTAINER_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
      - database
