version: "3"
services:
  frontend-react:
    image: frontend-react
    container_name: frontend-react
    build: ./frontend-react
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - ${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}
    depends_on:
      - backend
      
  backend:
    image: backend
    container_name: backend
    build: ./backend
    env_file:
      - .env
    ports:
      - 127.0.0.1:${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT} # Only required for accessing the API directly from the host


  database:
    image: database
    container_name: database
    build: ./database
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - ${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}